import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Pinyon_Script, Alex_Brush } from '@next/font/google';

const pinyonScript = Pinyon_Script({
  subsets: ['latin'],
  weight: "400"
});

const alex_brush = Alex_Brush({ subsets: ['latin'], weight: "400" })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${alex_brush.className}`} >

        {children}</body>
    </html>
  );
}