

import { Box, Typography } from '@mui/material';

import "@fontsource/pinyon-script"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <Box
        sx={{
          position: 'relative',
          width: '100%',
          height: '150px',
          backgroundImage: "url('/images/header_background2.jpg')",  // Update with your image path
          backgroundSize: '100% 100%',
          backgroundPosition: 'center',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
        }}
      >
        {/* Optional: Overlay */}
        <Box
          sx={{
            position: 'absolute',
            top: 0,
            left: 0,
            width: '100%',
            height: '100%',
            zIndex: 1,
          }}
        />

        {/* Centered Text */}
        <Typography
          variant="h2"
          sx={{
            color: 'black',
            fontWeight: 500,
            fontFamily: ["Pinyon Script", "cursive"].join(","),
            fontStyle: "normal",
            zIndex: 2,
            textAlign: 'center',
          }}
        >
          Dra Nicole Rivera
        </Typography>
      </Box >
      {children}
    </>
  )
}

